# Generated by Django 5.1.2 on 2025-01-07 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('folder_type', models.CharField(blank=True, choices=[('LIBRARY', 'Library'), ('SOURCE', 'Исходные данные'), ('PROCESS', 'Процесс работы'), ('TASKS', 'Обмен заданиями'), ('WORKING', 'Рабочие данные'), ('PUBLISHED', 'Опубликованные данные'), ('REMARKS', 'Замечания'), ('SHORTCUTS', 'Ярлыки')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='folders.folder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='projects.project')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
                'ordering': ['folder_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='project_files/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='folders.folder')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FolderAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('READ', 'Только чтение'), ('WRITE', 'Чтение и запись'), ('ADMIN', 'Полный доступ')], max_length=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rights', to='folders.folder')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_access', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ к папке',
                'verbose_name_plural': 'Доступы к папкам',
            },
        ),
        migrations.CreateModel(
            name='FolderActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('action_type', models.CharField(choices=[('CREATE', 'Создание'), ('UPDATE', 'Изменение'), ('DELETE', 'Удаление'), ('MOVE', 'Перемещение'), ('UPLOAD', 'Загрузка файла'), ('DOWNLOAD', 'Скачивание файла')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='folders.file')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='folders.folder')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог действий с папкой',
                'verbose_name_plural': 'Логи действий с папками',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['folder_type', 'project'], name='folders_fol_folder__101494_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['created_at'], name='folders_fol_created_f8980e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('project', 'folder_type', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='folderaccess',
            unique_together={('folder', 'user')},
        ),
    ]
