# Generated by Django 5.1.2 on 2025-01-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('source', models.CharField(max_length=255, verbose_name='Источник')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема')),
                ('link', models.URLField(max_length=1000, verbose_name='Ссылка')),
                ('published_date', models.CharField(max_length=100, verbose_name='Дата публикации')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL изображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
    ]
